name: continuous_integration_build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  continuous_integration_build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout_vave
      uses: actions/checkout@v4
    - name: checkout_cexil
      uses: actions/checkout@v4
      with:
        repository: alic3dev/cexil
        path: ../cexil
    - name: make_cexil
      run: cd ../cexil && make
    - name: make
      run: mkdir -p objects && make
